BERT

In [1]:
import torch

In [2]:
from models.transformer.blocks import *

In [6]:
mask = torch.triu(torch.ones(4,4),diagonal=1) == 0
mask

tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])

In [7]:
scores = torch.rand(1,2,4,4)
scores

tensor([[[[0.8379, 0.4635, 0.4502, 0.0441],
          [0.8712, 0.2328, 0.7188, 0.6917],
          [0.3422, 0.2308, 0.8964, 0.8887],
          [0.9431, 0.2510, 0.5992, 0.0061]],

         [[0.4750, 0.5827, 0.3024, 0.8821],
          [0.1186, 0.6957, 0.0535, 0.5438],
          [0.7093, 0.9174, 0.8147, 0.3325],
          [0.4350, 0.4647, 0.0284, 0.9987]]]])

In [8]:
scores.masked_fill(mask==0,1e-9)

tensor([[[[8.3791e-01, 1.0000e-09, 1.0000e-09, 1.0000e-09],
          [8.7122e-01, 2.3279e-01, 1.0000e-09, 1.0000e-09],
          [3.4224e-01, 2.3077e-01, 8.9642e-01, 1.0000e-09],
          [9.4313e-01, 2.5104e-01, 5.9916e-01, 6.0991e-03]],

         [[4.7502e-01, 1.0000e-09, 1.0000e-09, 1.0000e-09],
          [1.1860e-01, 6.9571e-01, 1.0000e-09, 1.0000e-09],
          [7.0934e-01, 9.1741e-01, 8.1472e-01, 1.0000e-09],
          [4.3500e-01, 4.6469e-01, 2.8376e-02, 9.9866e-01]]]])

In [21]:
# creating mask
pad = 0
batch = 3
seq_len = 4
a = torch.randint(0,10,(batch,seq_len))
a

tensor([[2, 1, 9, 7],
        [7, 0, 7, 9],
        [6, 0, 2, 7]])

In [22]:
sub_mask = subsequent_mask(seq_len)
sub_mask

tensor([[[ True, False, False, False],
         [ True,  True, False, False],
         [ True,  True,  True, False],
         [ True,  True,  True,  True]]])

In [28]:
pad_mask = a!=0
pad_mask

tensor([[ True,  True,  True,  True],
        [ True, False,  True,  True],
        [ True, False,  True,  True]])

In [46]:
# complete mask
mask = pad_mask.unsqueeze(-2) & sub_mask
mask

tensor([[[ True, False, False, False],
         [ True,  True, False, False],
         [ True,  True,  True, False],
         [ True,  True,  True,  True]],

        [[ True, False, False, False],
         [ True, False, False, False],
         [ True, False,  True, False],
         [ True, False,  True,  True]],

        [[ True, False, False, False],
         [ True, False, False, False],
         [ True, False,  True, False],
         [ True, False,  True,  True]]])

In [ ]:
# each seq a mask, which match the subsequent mask.
pad_mask.unsqueeze(-2)

tensor([[[ True,  True,  True,  True]],

        [[ True, False,  True,  True]],

        [[ True, False,  True,  True]]])

In [ ]:
# this makes the each token a mask instead of whole sequence
pad_mask.unsqueeze(-1)

tensor([[[ True],
         [ True],
         [ True],
         [ True]],

        [[ True],
         [False],
         [ True],
         [ True]],

        [[ True],
         [False],
         [ True],
         [ True]]])